export {default as HomeScreen} from './homeScreen'
export {default as SettingsScreen} from './settingsScreen'
export {default as AddEventScreen} from './addEventScreen'
export {default as EventDetailsScreen} from './eventDetailsScreen'
export {default as EventJoinersScreen} from './eventJoinersScreen'
export {default as AddPeopleScreen} from './addPeopleScreen'